### PR TITLE
Adding MONO8 format if number of channels is 1

### PR DESCRIPTION
**Pull request by sgermanserrano**
Picking up from #3 as it seems to have been abandoned

### CODE REVIEW

**Comment by sgermanserrano** [comment]
@OTL can you have a look?

**Comment by OTL** [comment]
It seems great!
What distro do you happy if I publish to?

**Comment by sgermanserrano** [comment]
@OTL noetic please

**Comment by OTL** [comment]
OK!

**Comment by sgermanserrano** [comment]
thanks a lot for the quick review!

**Comment by OTL** [comment]
I released it by bloom. Please wait for next sync!

**Pull request merged**
